---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users/{user_id}/cars":
    parameters:
      - name: user_id
        in: path
        description: user_id
        required: true
        schema:
          type: string
    get:
      summary: list cars
      responses:
        "200":
          description: successful
    post:
      summary: create car
      responses:
        "200":
          description: successful
  "/users/{user_id}/cars/{id}":
    parameters:
      - name: user_id
        in: path
        description: user_id
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
    get:
      summary: show car
      responses:
        "200":
          description: successful
    delete:
      summary: delete car
      responses:
        "200":
          description: successful
  "/cars":
    get:
      summary: list cars
      responses:
        "200":
          description: successful
  "/users/{user_id}/cars/{car_id}/reservations":
    parameters:
      - name: user_id
        in: path
        description: user_id
        required: true
        schema:
          type: string
      - name: car_id
        in: path
        description: car_id
        required: true
        schema:
          type: string
    get:
      summary: list reservations
      responses:
        "200":
          description: successful
    post:
      summary: create reservation
      responses:
        "200":
          description: successful
  "/users/{user_id}/cars/{car_id}/reservations/{id}":
    parameters:
      - name: user_id
        in: path
        description: user_id
        required: true
        schema:
          type: string
      - name: car_id
        in: path
        description: car_id
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
    get:
      summary: show reservation
      responses:
        "200":
          description: successful
    delete:
      summary: delete reservation
      responses:
        "200":
          description: successful
  "/users/{user_id}/reservations":
    parameters:
      - name: user_id
        in: path
        description: user_id
        required: true
        schema:
          type: string
    get:
      summary: list reservations
      responses:
        "200":
          description: successful
    post:
      summary: create reservation
      responses:
        "200":
          description: successful
  "/users/{user_id}/reservations/{id}":
    parameters:
      - name: user_id
        in: path
        description: user_id
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
    get:
      summary: show reservation
      responses:
        "200":
          description: successful
    delete:
      summary: delete reservation
      responses:
        "200":
          description: successful
servers:
  - url: https://{defaultHost}
    variables:
      defaultHost:
        default: www.example.com
